version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jarvis
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      DB_USER: root
      DB_PASS: secret
      DB_HOST: db
      DB_NAME: jarvis
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    volumes:
      - './frontend:/usr/share/nginx/html:ro'
    ports:
      - '8080:80'

volumes:
  db_data:
